web: cd backend && gunicorn library_seat_booking.wsgi:application
release: cd backend && python manage.py migrate
build: pip install -r backend/requirements.txt && cd backend && python manage.py collectstatic --noinput
python_version: "3.11"
